name: custom_services
description: A Flutter library with useful custom services.
version: 0.0.1
homepage: www.slickbit.de

publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_database: ^11.3.6
  firebase_messaging: ^15.2.6
  firebase_remote_config: ^5.4.4
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+1
  in_app_purchase_storekit: ^0.4.0
  in_app_purchase_platform_interface: ^1.3.5
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  universal_html: ^2.2.4
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.5
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
